# Generated by Django 4.0.3 on 2022-03-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_url',
            field=models.CharField(default='', max_length=215),
            preserve_default=False,
        ),
    ]
