# Generated by Django 4.0.3 on 2022-03-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_name',
        ),
    ]
