# Generated by Django 4.0.3 on 2022-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_song_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_name',
            field=models.CharField(default='', max_length=215),
            preserve_default=False,
        ),
    ]
