# Generated by Django 4.0.3 on 2022-03-12 12:17

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistr'),
        ('song', '0004_song_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=base.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongRecognitionResult',
            fields=[
                ('id', models.UUIDField(default=base.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('iscr', models.CharField(max_length=125)),
                ('upc', models.CharField(max_length=125)),
                ('release_date', models.DateField()),
                ('albums', models.ManyToManyField(to='song.album')),
                ('artists', models.ManyToManyField(to='artist.artistr')),
                ('genres', models.ManyToManyField(to='song.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
