# Generated by Django 4.0.3 on 2022-03-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_album_songrecognitionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrecognitionresult',
            name='albums',
        ),
        migrations.AddField(
            model_name='songrecognitionresult',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='song.album'),
            preserve_default=False,
        ),
    ]
