# Generated by Django 4.0.3 on 2022-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_rename_iscr_songrecognitionresult_isrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecognitionresult',
            name='bill_status',
            field=models.CharField(default='Pending', max_length=55),
        ),
    ]
