# Generated by Django 4.0.3 on 2022-03-17 15:38

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_songrecognitionresult_bill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorder',
            fields=[
                ('id', models.UUIDField(default=base.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=125, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
