# Generated by Django 4.0.3 on 2022-03-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_recorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecognitionresult',
            name='recorded_by',
            field=models.ForeignKey(default='ef494a90-523e-40ec-963d-3a63d11ce227', on_delete=django.db.models.deletion.CASCADE, to='song.recorder'),
            preserve_default=False,
        ),
    ]
